/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capa1;

import capa2.Materia;
import capa2.Profesor;
import capa3.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import capa2.Alumno;
import capa2.salon;
/**
 *
 * @author tepet
 */
public class ventalumno extends javax.swing.JFrame {

    /**
     * Creates new form ventalumno
     */
    public ventalumno() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTIDAlumno = new javax.swing.JTextField();
        jTNombrealum = new javax.swing.JTextField();
        jTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTIdmateria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 153));
        jLabel6.setText("SISTEMA DE ESTUDIANTES");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 340, 40));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 43, -1, -1));

        jTIDAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIDAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(jTIDAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 90, 30));

        jTNombrealum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombrealumActionPerformed(evt);
            }
        });
        getContentPane().add(jTNombrealum, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 200, 30));
        getContentPane().add(jTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 200, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setText("Registrar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 120, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bota.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 150, 80));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, 110, 60));
        getContentPane().add(jTIdmateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("Alumno");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 130, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Ingrese ID Materia");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/alum.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int idAlumno = 0;
            int idMateria =0;
        salon sal=new salon(idAlumno, idMateria);
           
         //       String materia;
           idAlumno=Integer.parseInt(jTIDAlumno.getText());
           idMateria=Integer.parseInt(jTIdmateria.getText());
     //    Alumno alu= new Alumno(idalumno);    
           
       // Materia mater= new Materia(idmateria);
       //       String al=sal.idAlumno();
     //     String mat=idMateria.toString();   
        //String al=idAlumno.toString();
          //String mat=idMateria.toString();
       
 //Directivo D1 = new Directivo(nombre =jTnombre.getText());  
   //      String d=D1.toString();
        // String text;
        String ins="";
      //  text=jTextField1.getText();
        ins="INSERT INTO salon (idAlumno, idMateria) VALUES (?,?)";
        try{
            PreparedStatement pst= conn.prepareStatement(ins);
            pst.setInt(1,idAlumno);
                pst.setInt(2,idMateria);
            int a=pst.executeUpdate();
            if(a>0){
                JOptionPane.showMessageDialog(null,"exitosa");
            }
            
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null,"error"+ ex);
        }
       /*    String ins2="";
      //  text=jTextField1.getText();
        ins2="INSERT INTO salon (idMateria) VALUES (?)";
        try{
            PreparedStatement pst= conn.prepareStatement(ins2);
        
            int a=pst.executeUpdate();    pst.setString(1,mat);
            if(a>0){
                JOptionPane.showMessageDialog(null,"exitosa");
            }
            
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null,"error"+ ex);
        }
     */
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTNombrealumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombrealumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombrealumActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTIDAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIDAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTIDAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventalumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventalumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventalumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventalumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventalumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JTextField jTIDAlumno;
    private javax.swing.JTextField jTIdmateria;
    public static javax.swing.JTextField jTNombrealum;
    public static javax.swing.JTextField jTelefono;
    // End of variables declaration//GEN-END:variables
 Conexion con=new Conexion();
        Connection conn=con.Conexion();
}
